=== rizoblo/MisEjercicios/Ejercicios/src/LenguajeMarcas/DTD/NewFile3.dtd
<!ELEMENT peliculas (pelicula)>
<!ELEMENT pelicula (director,pais,elenco,nombres)>
<!ELEMENT director EMPTY>
<!ELEMENT pais (#PCDATA | americano | europeo)*>
<!ELEMENT elenco (protagonistas*,secundarios+,cameos?)>
<!ELEMENT protagonistas ANY>
<!ELEMENT secundarios ANY>
<!ELEMENT cameos (#PCDATA)>
<!ELEMENT americano ANY>
<!ELEMENT europeo ANY>
<!ELEMENT nombres (nombre)*>
<!ELEMENT nombre ANY>


<!ENTITY % parametro "nombre CDATA #REQUIRED edad CDATA #REQUIRED">

<!ATTLIST director %parametro; nacionalidad NMTOKEN #REQUIRED>
<!ATTLIST cameos posibilidad CDATA #IMPLIED>
<!ATTLIST pais latino NMTOKEN #FIXED "no">
<!ATTLIST nombre procedencia ID #IMPLIED>
<!ATTLIST nombre procedencia ID #IMPLIED>
<!ATTLIST director tipoprocedencia IDREF #IMPLIED>
<!ATTLIST protagonistas %parametro; tipoprocedencia IDREFS #IMPLIED>
<!ATTLIST secundarios experiencia (alta | media | baja) #REQUIRED>



<!ENTITY lugar "occidental">

=== rizoblo/MisEjercicios/Ejercicios/src/LenguajeMarcas/DTD/NewFile3.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE peliculas SYSTEM "NewFile3.dtd">


<pelicula>

	<director nombre="paco" edad="39" nacionalidad="espaÃ±ola" tipoprocedencia="filipino"></director>

	<pais latino="no">
		<europeo>&lugar;</europeo>
	</pais>


	<elenco>
	
		<protagonistas nombre="pepe" edad="57" tipoprocedencia="filipino churrumino"></protagonistas>
	
	
		<secundarios experiencia="media"></secundarios>
		
		<cameos posibilidad="si"></cameos>
	
	</elenco>



	<nombres>
	
		<nombre procedencia="filipino"></nombre>
		<nombre procedencia="churrumino"></nombre>
		
	</nombres>


</pelicula>
