=== rizoblo/MisEjercicios/Ejercicios/src/LenguajeMarcas/DTD/NewFile2.dtd
<!ELEMENT provincias (provincia)>
<!ELEMENT provincia (nombre,rentas,codigo,situacion)>
<!ELEMENT nombre (poblacion+,clima?,renta*)>
<!ELEMENT codigo EMPTY>
<!ELEMENT poblacion (#PCDATA | mayoresedad | menoresedad)*>
<!ELEMENT clima ANY>
<!ELEMENT renta (rentapersonal)>
<!ELEMENT rentas (primertipo,segundotipo)>
<!ELEMENT mayoresedad (#PCDATA)>
<!ELEMENT menoresedad (#PCDATA)>
<!ELEMENT primertipo (#PCDATA)>
<!ELEMENT segundotipo (#PCDATA)>
<!ELEMENT rentapersonal ANY>
<!ELEMENT situacion ANY>


<!ENTITY % parametro "pais CDATA #REQUIRED">

<!ATTLIST poblacion numero (grande | mediana | pequeÃ±a) #IMPLIED>
<!ATTLIST clima calor CDATA #IMPLIED>
<!ATTLIST clima frio CDATA #FIXED "si">
<!ATTLIST clima %parametro; temple CDATA #REQUIRED>
<!ATTLIST primertipo cantidad ID #IMPLIED>
<!ATTLIST segundotipo cantidad ID #IMPLIED>
<!ATTLIST renta tiporenta IDREF #IMPLIED>
<!ATTLIST rentapersonal tiporenta IDREFS #IMPLIED>

<!ENTITY lugar "cordoba">

=== rizoblo/MisEjercicios/Ejercicios/src/LenguajeMarcas/DTD/NewFile2.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE provincias SYSTEM "NewFile2.dtd">


<provincia>


	<nombre>
		<poblacion numero="pequeÃ±a">
			<mayoresedad>18</mayoresedad>
		</poblacion>
		
		<clima frio="si" calor="no" pais="espaÃ±a" temple="no"></clima>
		
		<renta tiporenta="alta">
			<rentapersonal tiporenta="baja alta"></rentapersonal>
		
		</renta>
		
	</nombre>
	
	<rentas>
	
		<primertipo cantidad="alta"></primertipo>
		<segundotipo cantidad="baja"></segundotipo>
	
	</rentas>

	<codigo></codigo>

	<situacion>&lugar;</situacion>
</provincia>
