=== rizoblo/MisEjercicios/Ejercicios/src/LenguajeMarcas/DTD/NewFile1.dtd
<!ELEMENT centro (jefes,profesores,informacion)>
<!ELEMENT jefes (nivel?)>
<!ELEMENT profesores (asignatura*,alumnos+,padre*)>
<!ELEMENT nivel ANY>
<!ELEMENT asignatura (#PCDATA | guardia)*>
<!ELEMENT alumnos EMPTY>
<!ELEMENT guardia ANY>
<!ELEMENT informacion (nombre*,apellido*)>
<!ELEMENT nombre ANY>
<!ELEMENT apellido ANY>
<!ELEMENT padre ANY>



<!ENTITY % parametro "edad CDATA #IMPLIED">

<!ATTLIST asignatura materia CDATA #IMPLIED>
<!ATTLIST alumnos procedencia NMTOKENS #REQUIRED>
<!ATTLIST alumnos nacionalidad NMTOKEN #FIXED "espaÃ±a">
<!ATTLIST nombre nombre ID #IMPLIED>
<!ATTLIST apellido apellido ID #IMPLIED>

<!ATTLIST padre rellene_apellido IDREF #IMPLIED>
<!ATTLIST padre %parametro; rellene_nombre IDREF #IMPLIED>
<!ATTLIST alumnos %parametro; rellene_nombre IDREFS #IMPLIED>

<!ATTLIST jefes caracter (guay | noguay) #IMPLIED>

<!ENTITY cualificacion "alto">

=== rizoblo/MisEjercicios/Ejercicios/src/LenguajeMarcas/DTD/NewFile1.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE centro SYSTEM "NewFile1.dtd">

<centro>


	<jefes caracter="noguay">
	
		<nivel>&cualificacion;</nivel>
	
	
	</jefes>
	
	<profesores>
		
		<asignatura>
			<guardia></guardia>
		</asignatura>
		
		<alumnos procedencia="albaricoque" nacionalidad="espaÃ±a" edad="15" rellene_nombre="castellano aragones" ></alumnos>
		<padre edad="45" rellene_nombre="castellano" rellene_apellido="catalan"></padre>
	</profesores>
	
	<informacion>
		<nombre nombre="castellano"></nombre>
		<nombre nombre="aragones"></nombre>
		<apellido apellido="catalan"></apellido>
		
	
	</informacion>
	
</centro>
