=== rizoblo/MisEjercicios/Ejercicios/src/LenguajeMarcas/DTD/placasbase.dtd
<!ELEMENT placasbase (placaAsus, placaIntel)>
<!ELEMENT placaAsus (microprocesador | memoria | modelo | fabricante)*>
<!ELEMENT placaIntel (microprocesador | memoria | modelo | fabricante)*>

  <!ELEMENT microprocesador (#PCDATA)>
  <!ELEMENT memoria (#PCDATA)>
  <!ELEMENT modelo (#PCDATA)>
  <!ELEMENT fabricante (Asus | Intel)>
  <!ELEMENT Asus EMPTY>
  <!ELEMENT Intel EMPTY>

=== rizoblo/MisEjercicios/Ejercicios/src/LenguajeMarcas/DTD/ejercicioplacas.xml
<?xml version="1.0" encoding="UTF-8"?>


<!DOCTYPE placasbase SYSTEM "placasbase.dtd"> 


<placasbase>

  <placaAsus>
  
  <microprocesador>Pepe el del girasol</microprocesador>
  <memoria>juanito</memoria>
  <modelo>juan</modelo>
  <fabricante><Asus/></fabricante>
  
  </placaAsus>
  
  <placaIntel>
  
  <microprocesador>Pepe el del girasoles</microprocesador>
  <memoria>juanitos</memoria>
  <modelo>juanes</modelo>  
  <fabricante><Intel/></fabricante>
  
  </placaIntel>
 </placasbase>
