=== rizoblo/MisEjercicios/Ejercicios/src/LenguajeMarcas/Ejercicio2.dtd
<!ELEMENT emails (email*)>
<!ELEMENT email (para*,  cc*, cco*, asunto+, texto+, adjunto?)>
<!ELEMENT adjunto (nombre, mimetype, longitud)>

  <!ELEMENT para (#PCDATA)>
  <!ELEMENT cc (#PCDATA)>
  <!ELEMENT cco (#PCDATA)>
  <!ELEMENT asunto (#PCDATA)>
  <!ELEMENT texto (#PCDATA)>
  
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT mimetype (#PCDATA)>
  <!ELEMENT longitud (#PCDATA)>

=== rizoblo/MisEjercicios/Ejercicios/src/LenguajeMarcas/DTD/Ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE emails SYSTEM "Ejercicio2.dtd">


<emails>

  <email>
  
  <para></para>
  <cc></cc>
  <cco></cco>
  <asunto>ñaldsfjñalsdjf </asunto>
  <texto></texto>
  <adjunto>
  
  	<nombre></nombre>
  	<mimetype></mimetype>
  	<longitud></longitud>
  	
  </adjunto>	
  </email>
</emails>

=== rizoblo/MisEjercicios/Ejercicios/src/LenguajeMarcas/Ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE emails SYSTEM "Ejercicio2.dtd">


<emails>

  <email>
  
  <para>Pepe el del girasol</para><!ELEMENT nombre (#PCDATA)>
  <cc>juanito</cc>
  <cco>juan</cco>
  <asunto><Asus/></asunto>
  <texto></texto>
  <adjunto>
  
  	<nombre></nombre>
  	<mimetype></mimetype>
  	<longitud></longitud>
  	
  </adjunto>	
  </email>
</emails>
